### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-circleci-source#1]
**Requirements**
- Build out method to `/projects`
- Pass in API key as parameter

**Possible Config**
```
"config" : {
  "apiKey" : "976413b0iq12ebf7cf7a041bfb413650a509uny1",
  "method" : "projects"
}
```
**Relevant Links**
https://circleci.com/docs/api/
https://github.com/circleci/circleci-docs/blob/master/jekyll/_docs/api.md

**Comment by undercase** [comment]
Finished in last commit to dev.
